import Head from 'next/head';
import styles from '../../styles/Home.module.scss';
import Header from './Header';
import Footer from './Footer';
import { PropsWithChildren } from 'react';
import '../../styles/Header.module.css';

const Layout = (props: PropsWithChildren) => {
  return (
    <>
      <Head>
        <title>Apple TV+ - Apple</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="text/xml" href="/apple-logo.svg" />
        <link
          rel="stylesheet"
          href="https://www.apple.com/ac/globalnav/7/en_US/styles/ac-globalnav.built.css"
        />
      </Head>
      <Header />
      <main className={styles.main}>{props.children}</main>
      <Footer />
    </>
  );
};

export default Layout;
